# **1. Array Creation**

**1. Create a 1D NumPy array with values from 10 to 20.**

In [1]:
import numpy as np
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**2. Generate a 3x3 array filled with random integers between 0 and 50.**

In [2]:
b = np.random.rand(3,3)
c = np.random.randn(3,3)
print("Uniformly disrtibuted random numbers 3x3 array: \n")
print(b,"\n")
print("Standard / Normal disrtibuted random numbers 3x3 array: \n")
c

Uniformly disrtibuted random numbers 3x3 array: 

[[0.90595201 0.51752616 0.56840306]
 [0.92150841 0.92962449 0.6503671 ]
 [0.54730579 0.97240753 0.94195171]] 

Standard / Normal disrtibuted random numbers 3x3 array: 



array([[ 0.15161758,  0.82439549,  1.22514718],
       [-0.31163555,  0.88070241,  1.1101473 ],
       [ 0.32962003,  0.3777644 ,  0.07860223]])

**3. Create a 5x5 identity matrix**

In [3]:
d_float = np.eye(5)
d_int = np.eye(5, dtype = int)

print("Identity matrix with float numbers: \n",d_float,"\n")
print("Identity matrix with integer numbers: \n",d_int)

Identity matrix with float numbers: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

Identity matrix with integer numbers: 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


**Construct a 2D array with shape (3, 4), filled with the value 7.**

In [4]:
e = np.array([[7,7,7,7],[7,7,7,7],[7,7,7,7]])
print("The 3X4 2D array with value of 7 is: \n",e)
print("Shape of the matrix is",np.shape(e))

The 3X4 2D array with value of 7 is: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Shape of the matrix is (3, 4)


# **2. Array Indexing and Slicing**

**1. Extract the second row from the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]]**

In [23]:
f = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("The second row of the array is: \n",f[1])

The second row of the array is: 
 [4 5 6]


**2. Slice and print all elements in the first two rows and the last column of a 3x3 matrix.**

In [24]:
f = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("The first two rows and last column of the array is: \n",f[0:2,2])

The first two rows and last column of the array is: 
 [3 6]


**3. Reverse a 1D NumPy array: [5, 10, 15, 20] -> [20, 15, 10, 5].**

In [28]:
g = np.array([5, 10, 15, 20])
g_reversed = g[::-1]
print("All elements reversed: ",g_reversed)


All elements reversed:  [20 15 10  5]


# **Array Operations**

**1. Multiply all elements in an array by 2:
Input: [1, 2, 3] -> [2, 4, 6].**

In [27]:
h = np.array([1, 2, 3])
h_2 = h*2
print("All elements multiplied by 2: ",h_2)

All elements multiplied by 2:  [2 4 6]


**2. Calculate the sum of each row in a 3x3 matrix.**

In [33]:
#Taking above f 3X3 matrix
print("The matrix is: \n",f)
i = f.sum(axis = 1)
print("The row wise sum of all elements is: ",i)

The matrix is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The row wise sum of all elements is:  [ 6 15 24]


**3. Find the mean and standard deviation of the array:
[5, 10, 15, 20].**

In [36]:
j = ([5, 10, 15, 20])
print("Mean: ",np.mean(j))
print("Standard Deviation: ",np.std(j))

Mean:  12.5
Standard Deviation:  5.5901699437494745


**4. Boolean Operations**

**1. Find all elements greater than 10 in the array: [5, 10, 15, 20] and Replace all values in an array greater than 10 with 0.**

In [48]:
k = np.array([5,10,15,20])
mask = (k > 10)
print("All elements greater than 10: ",k[mask])

# Replace all elements greater than 10 with zero\
k[mask] = 0
print("\n Numbers greater than 10 replaced with 0: ",k)

All elements greater than 10:  [15 20]

 Numbers greater than 10 replaced with 0:  [ 5 10  0  0]


# **5. Linear Algebra with NumPy**

**1. Perform matrix multiplication for:**

In [51]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A.dot(B)


array([[19, 22],
       [43, 50]])

**2. Transpose of a Matrix and flatten**

In [60]:
array = np.array([[1, 2], [3, 4], [5, 6]])
print("Transpose of given matris is: \n",array.T)
print("\n Flattened Matrix: ",array.ravel())

Transpose of given matris is: 
 [[1 3 5]
 [2 4 6]]

 Flattened Matrix:  [1 2 3 4 5 6]


**3. Reshape a array**

In [65]:
oned_array = np.arange(12)
print("1D array is: ",oned_array)
new_array = oned_array.reshape(3,4)
print("\n Reshaped array in 3X4 is: \n",new_array)

1D array is:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array in 3X4 is: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
